# Generated by Django 3.2.5 on 2022-03-29 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload_clothes', '0001_initial'),
        ('accounts', '0002_auto_20220329_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='myphoto',
        ),
        migrations.AddField(
            model_name='profile',
            name='fitting_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/fitting_photo/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='my_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/my_photo/'),
        ),
        migrations.CreateModel(
            name='PreferCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer_cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_clothes.cloth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
