# Generated by Django 3.2.5 on 2022-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=10)),
                ('color_number', models.CharField(max_length=5)),
                ('color', models.CharField(max_length=20)),
                ('cloth_name', models.CharField(max_length=50)),
                ('cloth_price', models.BigIntegerField()),
                ('gender', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('cloth_image', models.ImageField(blank=True, null=True, upload_to='images/clothes/')),
                ('model_image', models.ImageField(blank=True, null=True, upload_to='images/models/')),
            ],
        ),
    ]
