# Generated by Django 3.2.5 on 2022-04-05 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fitting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload_clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPreferCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer_cloth_title', models.CharField(default='a.jpg', max_length=255, null=True)),
                ('prefer_cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_clothes.cloth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_photo_title', models.CharField(default='a.jpg', max_length=255, null=True)),
                ('my_photo', models.ImageField(blank=True, null=True, upload_to=fitting.models.change_uploaded_filename)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
